### ISSUE TITLE
enhancement: add systemd socket activation support

### ISSUE THREAD

**Issue by ilyapashuk** [brailcom/speechd#448] opened 2020-12-12 15:39 UTC
systemd is a service management system that is used by most of modern linux distro.

we already have systemd unit for SystemVide startup, but systemd also runs in every user session, managing user's own services.
for example, pulseaudio is working by such way.
one of very good features of systemd is socket activation.
this can work in the following way:
systemd, namely systemd, not speechd, listens on a $XDG_RUNTIME_DIR/speech-dispatcher/speechd.sock
when first client connection is created, it spawns speechd and switches this connection to it.
if speechd is already running, new connection will be given to existing instance.
so we will be able to fully drop our autospawning logic, that is implemented not by all clients, and fully switch to this way.

this also give an ability to easily view logs of speechd if it will be needed.

this requires server modification to make it to recieve new connections from systemd, but not to open socket by itself.
then the unit files in /etc/systemd/user should be created.

this will be especially usefull because many users noticed that in some times the speechd is not killed correctly on system shutdown, leading to some minutes hang up on every shutdown.
may be this is because orca is killed after it and respawns it before.
with systemd we will be able to forget about this completely because it will manage such things instead us.

**Comment by seb128** [comment] 2022-08-26 07:48
Having systemd socket activation is also require to get speech-dispatcher working with confined software as snaps and flatpaks. We are seeing the issue on Ubuntu with firefox now, the libspeechd from the snap doesn't have the required access to start speech-dispatcher by calling to the binary itself.

**Comment by lissyx** [comment] 2022-08-26 10:18
sounds to me like a dupe of https://github.com/brailcom/speechd/issues/336

**Comment by sthibaul** [comment] 2022-08-26 10:22
indeed, anybody working on the support should take into account the comments from both reports :)

**Comment by lissyx** [comment] 2022-09-28 18:09
So #336 was merged, this can be closed :)

**Comment by sthibaul** [comment] 2022-09-28 18:18
Yup :)

**Closed by sthibaul** 2022-09-28 18:18 UTC
Labels: enhancement, help wanted
